/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodtestscheduler;

import javax.swing.DefaultListModel;

/**
 *
 * @author Darren
 */
public class BTSGUI extends javax.swing.JFrame {

    //Creating models for my list boxes
    private DefaultListModel<String> currentListModel;
    private DefaultListModel<String> noShowListModel;
    String priority = "";

    /**
     * Creates new form BTSGUI
     */
    public BTSGUI() {
        initComponents();

        //Initializing Models
        currentListModel = new DefaultListModel<>();
        noShowListModel = new DefaultListModel<>();

        currentLIST.setModel(currentListModel);
        noShowLIST.setModel(noShowListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLBl = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        ageLBL = new javax.swing.JLabel();
        priorityLBL = new javax.swing.JLabel();
        wardLBL = new javax.swing.JLabel();
        gpLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        gpTF = new javax.swing.JTextField();
        requestBTN = new javax.swing.JButton();
        noShowBTN = new javax.swing.JButton();
        lowBTN = new javax.swing.JButton();
        mediumBTN = new javax.swing.JButton();
        urgentBTN = new javax.swing.JButton();
        yesBTN = new javax.swing.JButton();
        noBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        noShowLIST = new javax.swing.JList<>();
        noShowListLBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        currentLIST = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerLBl.setText("Blood Test Scheduler");

        nameLBL.setText("Name");

        ageLBL.setText("Age");

        priorityLBL.setText("Priority");

        wardLBL.setText("From Ward");

        gpLBL.setText("GP Details");

        requestBTN.setText("Request Test");
        requestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBTNActionPerformed(evt);
            }
        });

        noShowBTN.setText("No Show");
        noShowBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noShowBTNActionPerformed(evt);
            }
        });

        lowBTN.setText("Low");
        lowBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowBTNActionPerformed(evt);
            }
        });

        mediumBTN.setText("Medium");
        mediumBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumBTNActionPerformed(evt);
            }
        });

        urgentBTN.setText("Urgent");
        urgentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urgentBTNActionPerformed(evt);
            }
        });

        yesBTN.setText("Yes");
        yesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBTNActionPerformed(evt);
            }
        });

        noBTN.setText("No");
        noBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBTNActionPerformed(evt);
            }
        });

        noShowLIST.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(noShowLIST);

        noShowListLBL.setText("No Show List");

        currentLIST.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(currentLIST);

        jLabel1.setText("Current Queue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLBL)
                    .addComponent(ageLBL)
                    .addComponent(priorityLBL)
                    .addComponent(wardLBL)
                    .addComponent(gpLBL))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yesBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noBTN)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(requestBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lowBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mediumBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(urgentBTN))
                            .addComponent(ageTF)
                            .addComponent(nameTF)
                            .addComponent(gpTF))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLBl)
                .addGap(290, 290, 290))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(noShowBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(noShowListLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLBl)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLBL)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLBL)
                    .addComponent(ageTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priorityLBL)
                    .addComponent(lowBTN)
                    .addComponent(mediumBTN)
                    .addComponent(urgentBTN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wardLBL)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gpLBL)
                            .addComponent(gpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(yesBTN)
                        .addComponent(noBTN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(requestBTN)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noShowBTN)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noShowListLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Method that retrieves Patient info and adds them to List
    private void requestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBTNActionPerformed
        // TODO add your handling code here:
        String name = nameTF.getText();
        int age = Integer.parseInt(ageTF.getText());
        String priority = getSelectedPriority();
        boolean fromWard = yesBTN.isSelected();
        String gpDetails = gpTF.getText();

        //Create a new patient
        Patient newPatient = new Patient(name, age, priority, fromWard, gpDetails);

        //Adds Patient to list when Request button is pressed
        currentListModel.addElement(newPatient.toString());

        //Clear the form fields after adding
        nameTF.setText("");
        ageTF.setText("");
        gpTF.setText("");
    }//GEN-LAST:event_requestBTNActionPerformed

    private void noShowBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noShowBTNActionPerformed
        // TODO add your handling code here:

        //Selects patient from 'Current Queue' List
        String selectedPatient = currentLIST.getSelectedValue();

        if (selectedPatient != null) {
            // Remove from 'Current Queue' List and adds them to 'No Show List'
            currentListModel.removeElement(selectedPatient);
            noShowListModel.addElement(selectedPatient);
        }
    }//GEN-LAST:event_noShowBTNActionPerformed
    
    // Adding functionality to ALL Buttons
    private void setPriority(String priority) {
        this.priority = priority;
    }

    private void lowBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowBTNActionPerformed
        // TODO add your handling code here:
        setPriority("Low");
    }//GEN-LAST:event_lowBTNActionPerformed

    private void mediumBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumBTNActionPerformed
        // TODO add your handling code here:
        setPriority("Medium");
    }//GEN-LAST:event_mediumBTNActionPerformed

    private void urgentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urgentBTNActionPerformed
        // TODO add your handling code here:
        setPriority("Urgent");
    }//GEN-LAST:event_urgentBTNActionPerformed

    private void yesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBTNActionPerformed
        // TODO add your handling code here:
        yesBTN.setSelected(true);
        noBTN.setSelected(false);
    }//GEN-LAST:event_yesBTNActionPerformed

    private void noBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBTNActionPerformed
        // TODO add your handling code here:
        noBTN.setSelected(true);
        yesBTN.setSelected(false);
    }//GEN-LAST:event_noBTNActionPerformed

    //Priority selection method 
    private String getSelectedPriority() {
        return priority;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BTSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BTSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BTSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BTSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BTSGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLBL;
    private javax.swing.JTextField ageTF;
    private javax.swing.JList<String> currentLIST;
    private javax.swing.JLabel gpLBL;
    private javax.swing.JTextField gpTF;
    private javax.swing.JLabel headerLBl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lowBTN;
    private javax.swing.JButton mediumBTN;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton noBTN;
    private javax.swing.JButton noShowBTN;
    private javax.swing.JList<String> noShowLIST;
    private javax.swing.JLabel noShowListLBL;
    private javax.swing.JLabel priorityLBL;
    private javax.swing.JButton requestBTN;
    private javax.swing.JButton urgentBTN;
    private javax.swing.JLabel wardLBL;
    private javax.swing.JButton yesBTN;
    // End of variables declaration//GEN-END:variables
}
